name: Block Invalid Release Branches

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  block-invalid-release-pr:
    uses: salva133/My-Workflows/.github/workflows/block-invalid-release-branches.yml@7229769e5562f12fc2a33062b309e3d396eaf0ef
    with:
      head_ref: ${{ github.head_ref }}
